insert into aluno(nome,cpf) values
('Adonias Filho','1'),
('Affonso Arinos de Mello Franco','2'),
('Afonso Escragnolle Taunay','3'),
('Afonso Pena Júnior','4'),
('Afrânio Coutinho','5'),
('Alberto de Faria','6'),
('Alberto Faria','7'),
('Antônio Mariano de Oliveira','8'),
('Alberto Venancio Filho','9'),
('Alceu Amoroso Lima','10'),
('Alcides Maia','11'),
('Alcindo Guanabara','12'),
('Alfredo Bosi','13'),
('Alfredo Escragnolle Taunay','14'),
('Alfredo Pujol','15'),
('Aluísio Azevedo','16'),
('Álvaro Lins','17'),
('Álvaro Moreyra','18'),
('Amadeu Amaral','19'),
('Américo Jacobina Lacombe','20'),
('Ana Maria Machado','21'),
('Antônio Calado','22'),
('Antônio Carlos Secchin','23'),
('Antônio Carneiro Leão','24'),
('Antônio de Castro Assunção','25'),
('Antônio Joaquim Pereira da Silva','26'),
('Antônio Olinto','27'),
('Antônio da Silva Melo','28'),
('Antônio Torres','29'),
('Araripe Júnior','30'),
('Ariano Suassuna','31'),
('Artur de Azevedo','32'),
('Artur Jaceguai','33'),
('Artur Orlando da Silva','34'),
('Assis Chateaubriand','35'),
('Augusto Meyer','36'),
('Aurélio de Lira Tavares','37'),
('Bernardo Élis','38'),
('Camillo Cavalcanti/Alceu Amoroso Lima','39'),
('Cândido Mendes de Almeida','40'),
('Cândido Mota Filho','41'),
('Carlos Castelo Branco','42'),
('Carlos Chagas Filho','43'),
('Carlos Heitor Cony','44'),
('Carlos Magalhães de Azeredo','45'),
('Carlos Nejar','46'),
('Cassiano Ricardo','47'),
('Celso Ferreira da Cunha','48'),
('Celso Furtado','49'),
('Celso Lafer','50'),
('Ciro dos Anjos','51'),
('Clementino Fraga','52'),
('Clóvis Beviláqua','53'),
('Constâncio Alves','54'),
('Dantas Barreto','55'),
('Darcy Ribeiro','56'),
('Deolindo Couto','57'),
('Dias Gomes','58'),
('Diná Silveira de Queirós','59'),
('Domício Proença Filho','60'),
('Edgar Roquette Pinto','61'),
('Eduardo Paulo da Silva Prado','62'),
('Eduardo Portella','63'),
('Eduardo Ramos','64'),
('Emílio de Meneses','65'),
('Euclides da Cunha','66'),
('Evaldo Cabral de Mello','67'),
('Evandro Lins e Silva','68'),
('Evanildo Bechara','69'),
('Evaristo de Moraes Filho','70'),
('Félix Pacheco','71'),
('Fernando de Azevedo','72'),
('Fernando Bastos de Ávila','73'),
('Fernando Henrique Cardoso','74'),
('Ferreira Gullar','75'),
('Filinto de Almeida','76'),
('Francisco de Aquino Correia','77'),
('Francisco de Assis Barbosa','78'),
('Francisco de Castro','79'),
('Francisco Cavalcanti Pontes de Miranda','80'),
('Francisco Inácio Marcondes Homem de Melo','81'),
('Franklin Dória','82'),
('Garcia Redondo','83'),
('Genolino Amado','84'),
('Geraldo França de Lima','85'),
('Geraldo Holanda Cavalcanti','86'),
('Getúlio Vargas','87'),
('Gilberto Amado','88'),
('Graça Aranha','89'),
('Gregório da Fonseca','90'),
('Guilherme de Almeida','91'),
('Guimarães Júnior','92'),
('Guimarães Passos','93'),
('Guimarães Rosa','94'),
('Hélio Jaguaribe','95'),
('Hélio Lobo','96'),
('Heráclito Graça','97'),
('Herberto Sales','98'),
('Hermes Lima','99'),
('Humberto de Campos','100'),
('Inglês de Sousa','101'),
('Ivan Monteiro de Barros Lins','102'),
('Ivo Pitanguy','103'),
('João Batista Ribeiro de Andrade Fernandes','104'),
('João Cabral de Melo Neto','105'),
('João Carneiro de Sousa Bandeira','106'),
('João do Rio','107'),
('João Luís Alves','108'),
('João Manuel Pereira da Silva','109'),
('João de Scantimburgo','110'),
('João Ubaldo Ribeiro','111'),
('Joracy Camargo','112'),
('Jorge Amado','113'),
('José de Alcântara Machado','114'),
('José Américo de Almeida','115'),
('José Cândido de Carvalho','116'),
('José Guilherme Merquior','117'),
('José Honório Rodrigues','118'),
('José Júlio da Silva Ramos','119'),
('José Lins do Rego','120'),
('José Maria da Silva Paranhos Júnior','121'),
('José Maria Goulart de Andrade','122'),
('José Maria da Silva Paranhos','123'),
('José Mindlin','124'),
('José Murilo de Carvalho','125'),
('José do Patrocínio','126'),
('José Sarney','127'),
('José Veríssimo','128'),
('Lafayette Rodrigues Pereira','129'),
('Lauro Müller','130'),
('Lêdo Ivo','131'),
('Lucas Moreira Neves','132'),
('Lúcio de Mendonça','133'),
('Luís Carlos da Fonseca Monteiro de Barros','134'),
('Luís Edmundo','135'),
('Luís Guimarães Filho','136'),
('Luís Murat','137'),
('Luís Viana Filho','138'),
('Luiz Paulo Horta','139'),
('Lygia Fagundes Telles','140'),
('Manuel Bandeira','141'),
('Manuel de Oliveira Lima','142'),
('Marco Lucchesi','143'),
('Marco Maciel','144'),
('Marcos Almir Madeira','145'),
('Marcos Barbosa','146'),
('Mário de Alencar','147'),
('Mário Palmério','148'),
('Marques Rebelo','149'),
('Maurício Campos de Medeiros','150'),
('Mauro Mota','151'),
('Menotti Del Picchia','152'),
('Merval Pereira','153'),
('Miguel Couto','154'),
('Miguel Reale','155'),
('Moacyr Scliar','156'),
('Murilo Melo Filho','157'),
('Nelson Pereira dos Santos','158'),
('Odilo Costa Filho','159'),
('Olavo Bilac','160'),
('Olegário Mariano','161'),
('Oliveira Viana','162'),
('Orígenes Lessa','163'),
('Oscar Dias Correia','164'),
('Osório Duque Estrada','165'),
('Osvaldo Cruz','166'),
('Osvaldo Orico','167'),
('Otávio de Faria','168'),
('Otávio Mangabeira','169'),
('Otto Lara Resende','170'),
('Paulo Carneiro','171'),
('Paulo Coelho','172'),
('Paulo Setúbal','173'),
('Pedro Lessa','174'),
('Pedro Rabelo','175'),
('Rachel de Queiroz','176'),
('Raimundo Correia','177'),
('Raimundo Faoro','178'),
('Raimundo Magalhães Júnior','179'),
('Ribeiro Couto','180'),
('Roberto Campos','181'),
('Roberto Marinho','182'),
('Roberto Simonsen','183'),
('Rocha Pombo','184'),
('Rodolfo Garcia','185'),
('Rosiska Darcy de Oliveira','186'),
('Sábato Magaldi','187'),
('Salvador de Mendonça','188'),
('Santos Dumont','189'),
('Sérgio Correia da Costa','190'),
('Sérgio Paulo Rouanet','191'),
('Silvério Gomes Pimenta','192'),
('Sílvio Romero','193'),
('Teixeira de Melo','194'),
('Urbano Duarte de Oliveira','195'),
('Valentim Magalhães','196');